funder:
  available:
    - funder: "Austrian Science Fund"
      doi: "10.13039/501100002428"
    - funder: "European Commission"
      doi: "10.13039/501100000780"
    - funder: "European Environment Agency"
      doi: "10.13039/501100000806"
    - funder: "Academy of Finland"
      doi: "10.13039/501100002341"
    - funder: "Hrvatska Zaklada za Znanost"
      doi: "10.13039/501100004488"
    - funder: "Fundação para a Ciência e a Tecnologia"
      doi: "10.13039/501100001871"
    - funder: "Ministarstvo Prosvete, Nauke i Tehnološkog Razvoja"
      doi: "10.13039/501100004564"
    - funder: "Ministarstvo Znanosti, Obrazovanja i Sporta"
      doi: "10.13039/501100006588"
    - funder: "National Health and Medical Research Council"
      doi: "10.13039/501100000925"
    - funder: "National Institutes of Health"
      doi: "10.13039/100000002"
    - funder: "National Science Foundation"
      doi: "10.13039/100000001"
    - funder: "Nederlandse Organisatie voor Wetenschappelijk Onderzoek"
      doi: "10.13039/501100003246"
    - funder: "Research Councils"
      doi: "10.13039/501100000690"
    - funder: "Schweizerischer Nationalfonds zur Förderung der wissenschaftlichen Forschung"
      doi: "10.13039/501100001711"
    - funder: "Science Foundation Ireland"
      doi: "10.13039/501100001602"
    - funder: "Wellcome Trust"
      doi: "10.13039/100004440"