identifiers:
  related:
    - zenodo.related_identifiers.isCitedBy
    - zenodo.related_identifiers.cites
    - zenodo.related_identifiers.isSupplementTo
    - zenodo.related_identifiers.isSupplementedBy
    - zenodo.related_identifiers.isContinuedBy
    - zenodo.related_identifiers.continues
    - zenodo.related_identifiers.isDescribedBy
    - zenodo.related_identifiers.describes
    - zenodo.related_identifiers.hasMetadata
    - zenodo.related_identifiers.isMetadataFor
    - zenodo.related_identifiers.isNewVersionOf
    - zenodo.related_identifiers.isPreviousVersionOf
    - zenodo.related_identifiers.isPartOf
    - zenodo.related_identifiers.hasPart
    - zenodo.related_identifiers.isReferencedBy
    - zenodo.related_identifiers.references
    - zenodo.related_identifiers.isDocumentedBy
    - zenodo.related_identifiers.documents
    - zenodo.related_identifiers.isCompiledBy
    - zenodo.related_identifiers.compiles
    - zenodo.related_identifiers.isVariantFormOf
    - zenodo.related_identifiers.isOriginalFormof
    - zenodo.related_identifiers.isIdenticalTo
    - zenodo.related_identifiers.isAlternateIdentifier
    - zenodo.related_identifiers.isReviewedBy
    - zenodo.related_identifiers.reviews
    - zenodo.related_identifiers.isDerivedFrom
    - zenodo.related_identifiers.isSourceOf
    - zenodo.related_identifiers.requires
    - zenodo.related_identifiers.isRequiredBy
    - zenodo.related_identifiers.isObsoletedBy
    - zenodo.related_identifiers.obsoletes