idpclient:
  claims:
    mapping:
      Subject:
        - type: sub
      Name:
        - type: name
      Client:
        - type: client_id
      AuthenticationMethod:
        - type: amr
      NotBefore:
        - type: nbf
      AuthenticatedAt:
        - type: auth_time
      ExpiresAt:
        - type: exp
      Email:
        - type: email
      Roles:
        - type: resource_access
          path: dmp_zenodo_bridge.roles
      Scope:
        - type: scope
      AccessToken:
        - type: x-access-token
          visibility: SENSITIVE
      IssuedAt:
        - type: iat
      Issuer:
        - type: iss
      Audience:
        - type: aud
      TokenType:
        - type: typ
      AuthorizedParty:
        - type: azp
      Authorities:
        - type: authorities
      ExternalProviderName:
        - type: identity_provider