pid:
  fields:
    pid-name: pid
    pid-type-name: pidTypeField
  accepted-types:
    - actrn
    - ark
    - bibcode
    - nct
    - drks
    - doi
    - euctr
    - data.europa.eu
    - epo_id
    - GRID
    - gsk
    - GeoPass
    - GBIF
    - hal
    - handle
    - isrctn
    - ichushi
    - ISNI
    - jprn
    - mag_id
    - NAID
    - NCID
    - oai
    - orcid_pending
    - orcid
    - OrgPeg
    - PANGAEA
    - PIC
    - epo_nr_epodoc
    - pdb
    - pmc
    - pmid
    - RNSR
    - ROR
    - RRID
    - UNKNOWN
    - VIAF
    - who
    - arXiv
    - info:eu-repo/dai
    - orcidworkid
    - urn
    - w3id