programming-languages:
    programming-codes:
        - 1c_enterprise
        - 2_dimensional_array
        - 4d
        - abap
        - abap_cds
        - abnf
        - ags_script
        - aidl
        - al
        - ampl
        - antlr
        - api_blueprint
        - apl
        - asl
        - asn.1
        - asp.net
        - ats
        - actionscript
        - ada
        - adblock_filter_list
        - adobe_font_metrics
        - agda
        - alloy
        - alpine_abuild
        - altium_designer
        - angelscript
        - ant_build_system
        - antlers
        - apacheconf
        - apex
        - apollo_guidance_computer
        - applescript
        - arc
        - asciidoc
        - aspectj
        - assembly
        - astro
        - asymptote
        - augeas
        - autohotkey
        - autoit
        - avro_idl
        - awk
        - basic
        - ballerina
        - batchfile
        - beef
        - befunge
        - berry
        - bibtex
        - bicep
        - bikeshed
        - bison
        - bitbake
        - blade
        - blitzbasic
        - blitzmax
        - bluespec
        - bluespec_bh
        - boo
        - boogie
        - brainfuck
        - brighterscript
        - brightscript
        - browserslist
        - c
        - c#
        - c++
        - c_objdump
        - c2hs_haskell
        - cap_cds
        - cil
        - clips
        - cmake
        - cobol
        - codeowners
        - collada
        - cson
        - css
        - csv
        - cue
        - cweb
        - cabal_config
        - cadence
        - cairo
        - cameligo
        - cap'n_proto
        - cartocss
        - ceylon
        - chapel
        - charity
        - checksums
        - chuck
        - circom
        - cirru
        - clarion
        - clarity
        - classic_asp
        - clean
        - click
        - clojure
        - closure_templates
        - cloud_firestore_security_rules
        - conll_u
        - codeql
        - coffeescript
        - coldfusion
        - coldfusion_cfc
        - common_lisp
        - common_workflow_language
        - component_pascal
        - cool
        - coq
        - cpp_objdump
        - creole
        - crystal
        - csound
        - csound_document
        - csound_score
        - cuda
        - cue_sheet
        - curry
        - cycript
        - cypher
        - cython
        - d
        - d_objdump
        - d2
        - digital_command_language
        - dm
        - dns_zone
        - dtrace
        - dafny
        - darcs_patch
        - dart
        - dataweave
        - debian_package_control_file
        - denizenscript
        - dhall
        - diff
        - directx_3d_file
        - dockerfile
        - dogescript
        - dotenv
        - dylan
        - e
        - e_mail
        - ebnf
        - ecl
        - eclipse
        - ejs
        - eq
        - eagle
        - earthly
        - easybuild
        - ecere_projects
        - ecmarkup
        - editorconfig
        - edje_data_collection
        - eiffel
        - elixir
        - elm
        - elvish
        - elvish_transcript
        - emacs_lisp
        - emberscript
        - erlang
        - euphoria
        - f#
        - f*
        - figlet_font
        - flux
        - factor
        - fancy
        - fantom
        - faust
        - fennel
        - filebench_wml
        - filterscript
        - fluent
        - formatted
        - forth
        - fortran
        - fortran_free_form
        - freebasic
        - freemarker
        - frege
        - futhark
        - g_code
        - gaml
        - gams
        - gap
        - gcc_machine_description
        - gdb
        - gdscript
        - gedcom
        - glsl
        - gn
        - gsc
        - game_maker_language
        - gemfile.lock
        - gemini
        - genero
        - genero_forms
        - genie
        - genshi
        - gentoo_ebuild
        - gentoo_eclass
        - gerber_image
        - gettext_catalog
        - gherkin
        - git_attributes
        - git_config
        - git_revision_list
        - gleam
        - glyph
        - glyph_bitmap_distribution_format
        - gnuplot
        - go
        - go_checksums
        - go_module
        - go_workspace
        - godot_resource
        - golo
        - gosu
        - grace
        - gradle
        - gradle_kotlin_dsl
        - grammatical_framework
        - graph_modeling_language
        - graphql
        - graphviz_(dot)
        - groovy
        - groovy_server_pages
        - haproxy
        - hcl
        - hlsl
        - hocon
        - html
        - html+ecr
        - html+eex
        - html+erb
        - html+php
        - html+razor
        - http
        - hxml
        - hack
        - haml
        - handlebars
        - harbour
        - haskell
        - haxe
        - hiveql
        - holyc
        - hosts_file
        - hy
        - hyphy
        - idl
        - igor_pro
        - ini
        - irc_log
        - idris
        - ignore_list
        - imagej_macro
        - imba
        - inform_7
        - ink
        - inno_setup
        - io
        - ioke
        - isabelle
        - isabelle_root
        - j
        - jar_manifest
        - jcl
        - jflex
        - json
        - json_with_comments
        - json5
        - jsonld
        - jsoniq
        - janet
        - jasmin
        - java
        - java_properties
        - java_server_pages
        - javascript
        - javascript+erb
        - jest_snapshot
        - jetbrains_mps
        - jinja
        - jison
        - jison_lex
        - jolie
        - jsonnet
        - julia
        - jupyter_notebook
        - just
        - krl
        - kaitai_struct
        - kakounescript
        - kerboscript
        - kicad_layout
        - kicad_legacy_layout
        - kicad_schematic
        - kickstart
        - kit
        - kotlin
        - kusto
        - lfe
        - llvm
        - lolcode
        - lsl
        - ltspice_symbol
        - labview
        - lark
        - lasso
        - latte
        - lean
        - less
        - lex
        - ligolang
        - lilypond
        - limbo
        - linker_script
        - linux_kernel_module
        - liquid
        - literate_agda
        - literate_coffeescript
        - literate_haskell
        - livescript
        - logos
        - logtalk
        - lookml
        - loomscript
        - lua
        - m
        - m4
        - m4sugar
        - matlab
        - maxscript
        - mdx
        - mlir
        - mql4
        - mql5
        - mtml
        - muf
        - macaulay2
        - makefile
        - mako
        - markdown
        - marko
        - mask
        - mathematica
        - maven_pom
        - max
        - mercury
        - mermaid
        - meson
        - metal
        - microsoft_developer_studio_project
        - microsoft_visual_studio_solution
        - minid
        - miniyaml
        - mint
        - mirah
        - modelica
        - modula_2
        - modula_3
        - module_management_system
        - monkey
        - monkey_c
        - moocode
        - moonscript
        - motoko
        - motorola_68k_assembly
        - move
        - muse
        - mustache
        - myghty
        - nasl
        - ncl
        - neon
        - nl
        - npm_config
        - nsis
        - nwscript
        - nasal
        - nearley
        - nemerle
        - netlinx
        - netlinx+erb
        - netlogo
        - newlisp
        - nextflow
        - nginx
        - nim
        - ninja
        - nit
        - nix
        - nu
        - numpy
        - nunjucks
        - nushell
        - oasv2_json
        - oasv2_yaml
        - oasv3_json
        - oasv3_yaml
        - ocaml
        - objdump
        - object_data_instance_notation
        - objectscript
        - objective_c
        - objective_c++
        - objective_j
        - odin
        - omgrofl
        - opa
        - opal
        - open_policy_agent
        - openapi_specification_v2
        - openapi_specification_v3
        - opencl
        - openedge_abl
        - openqasm
        - openrc_runscript
        - openscad
        - openstep_property_list
        - opentype_feature_file
        - option_list
        - org
        - ox
        - oxygene
        - oz
        - p4
        - pddl
        - peg.js
        - php
        - plsql
        - plpgsql
        - pov_ray_sdl
        - pact
        - pan
        - papyrus
        - parrot
        - parrot_assembly
        - parrot_internal_representation
        - pascal
        - pawn
        - pep8
        - perl
        - pic
        - pickle
        - picolisp
        - piglatin
        - pike
        - plantuml
        - pod
        - pod_6
        - pogoscript
        - polar
        - pony
        - portugol
        - postcss
        - postscript
        - powerbuilder
        - powershell
        - prisma
        - processing
        - procfile
        - proguard
        - prolog
        - promela
        - propeller_spin
        - protocol_buffer
        - protocol_buffer_text_format
        - public_key
        - pug
        - puppet
        - pure_data
        - purebasic
        - purescript
        - pyret
        - python
        - python_console
        - python_traceback
        - q#
        - qml
        - qmake
        - qt_script
        - quake
        - r
        - raml
        - rbs
        - rdoc
        - realbasic
        - rexx
        - rmarkdown
        - rpc
        - rpgle
        - rpm_spec
        - runoff
        - racket
        - ragel
        - raku
        - rascal
        - raw_token_data
        - rescript
        - readline_config
        - reason
        - reasonligo
        - rebol
        - record_jar
        - red
        - redcode
        - redirect_rules
        - regular_expression
        - ren'py
        - renderscript
        - rez
        - rich_text_format
        - ring
        - riot
        - robotframework
        - roff
        - roff_manpage
        - rouge
        - routeros_script
        - ruby
        - rust
        - sas
        - scss
        - selinux_policy
        - smt
        - sparql
        - sqf
        - sql
        - sqlpl
        - srecode_template
        - ssh_config
        - star
        - stl
        - ston
        - svg
        - swig
        - sage
        - saltstack
        - sass
        - scala
        - scaml
        - scenic
        - scheme
        - scilab
        - self
        - shaderlab
        - shell
        - shellcheck_config
        - shellsession
        - shen
        - sieve
        - simple_file_verification
        - singularity
        - slash
        - slice
        - slim
        - smpl
        - smali
        - smalltalk
        - smarty
        - smithy
        - snakemake
        - solidity
        - soong
        - sourcepawn
        - spline_font_database
        - squirrel
        - stan
        - standard_ml
        - starlark
        - stata
        - stringtemplate
        - stylus
        - subrip_text
        - sugarss
        - supercollider
        - svelte
        - sway
        - sweave
        - swift
        - systemverilog
        - ti_program
        - tl_verilog
        - tla
        - toml
        - tsql
        - tsv
        - tsx
        - txl
        - talon
        - tcl
        - tcsh
        - tex
        - tea
        - terra
        - texinfo
        - text
        - textmate_properties
        - textile
        - thrift
        - turing
        - turtle
        - twig
        - type_language
        - typescript
        - typst
        - unified_parallel_c
        - unity3d_asset
        - unix_assembly
        - uno
        - unrealscript
        - urweb
        - v
        - vba
        - vbscript
        - vcl
        - vhdl
        - vala
        - valve_data_format
        - velocity_template_language
        - verilog
        - vim_help_file
        - vim_script
        - vim_snippet
        - visual_basic_.net
        - visual_basic_6.0
        - volt
        - vue
        - vyper
        - wdl
        - wgsl
        - wavefront_material
        - wavefront_object
        - web_ontology_language
        - webassembly
        - webassembly_interface_type
        - webidl
        - webvtt
        - wget_config
        - whiley
        - wikitext
        - win32_message_file
        - windows_registry_entries
        - witcher_script
        - wollok
        - world_of_warcraft_addon_data
        - wren
        - x_bitmap
        - x_font_directory_index
        - x_pixmap
        - x10
        - xc
        - xcompose
        - xml
        - xml_property_list
        - xpages
        - xproc
        - xquery
        - xs
        - xslt
        - xojo
        - xonsh
        - xtend
        - yaml
        - yang
        - yara
        - yasnippet
        - yacc
        - yul
        - zap
        - zil
        - zeek
        - zenscript
        - zephir
        - zig
        - zimpl
        - curl_config
        - desktop
        - dircolors
        - ec
        - edn
        - fish
        - hoon
        - jq
        - kvlang
        - mirc_script
        - mcfunction
        - mupad
        - nanorc
        - nesc
        - ooc
        - q
        - restructuredtext
        - robots.txt
        - sed
        - wisp
        - xbase
    development-status:
        - wip
        - unsupported
        - inactive
        - suspended
        - moved
        - concept
        - abandoned
        - active