semantics:
  related-identifiers:
    - zenodo.related_identifiers.isCitedBy
    - zenodo.related_identifiers.cites
    - zenodo.related_identifiers.isSupplementTo
    - zenodo.related_identifiers.isSupplementedBy
    - zenodo.related_identifiers.isContinuedBy
    - zenodo.related_identifiers.continues
    - zenodo.related_identifiers.isDescribedBy
    - zenodo.related_identifiers.describes
    - zenodo.related_identifiers.hasMetadata
    - zenodo.related_identifiers.isMetadataFor
    - zenodo.related_identifiers.isNewVersionOf
    - zenodo.related_identifiers.isPreviousVersionOf
    - zenodo.related_identifiers.isPartOf
    - zenodo.related_identifiers.hasPart
    - zenodo.related_identifiers.isReferencedBy
    - zenodo.related_identifiers.references
    - zenodo.related_identifiers.isDocumentedBy
    - zenodo.related_identifiers.documents
    - zenodo.related_identifiers.isCompiledBy
    - zenodo.related_identifiers.compiles
    - zenodo.related_identifiers.isVariantFormOf
    - zenodo.related_identifiers.isOriginalFormof
    - zenodo.related_identifiers.isIdenticalTo
    - zenodo.related_identifiers.isAlternateIdentifier
    - zenodo.related_identifiers.isReviewedBy
    - zenodo.related_identifiers.reviews
    - zenodo.related_identifiers.isDerivedFrom
    - zenodo.related_identifiers.isSourceOf
    - zenodo.related_identifiers.requires
    - zenodo.related_identifiers.isRequiredBy
    - zenodo.related_identifiers.isObsoletedBy
    - zenodo.related_identifiers.obsoletes
  related-identifiers-scheme:
    - zenodo.related_identifiers.scheme.ark
    - zenodo.related_identifiers.scheme.arxiv
    - zenodo.related_identifiers.scheme.ads
    - zenodo.related_identifiers.scheme.crossreffunderid
    - zenodo.related_identifiers.scheme.doi
    - zenodo.related_identifiers.scheme.ean13
    - zenodo.related_identifiers.scheme.eissn
    - zenodo.related_identifiers.scheme.grid
    - zenodo.related_identifiers.scheme.handle
    - zenodo.related_identifiers.scheme.igsn
    - zenodo.related_identifiers.scheme.isbn
    - zenodo.related_identifiers.scheme.isni
    - zenodo.related_identifiers.scheme.issn
    - zenodo.related_identifiers.scheme.istc
    - zenodo.related_identifiers.scheme.lissn
    - zenodo.related_identifiers.scheme.lsid
    - zenodo.related_identifiers.scheme.pmid
    - zenodo.related_identifiers.scheme.purl
    - zenodo.related_identifiers.scheme.upc
    - zenodo.related_identifiers.scheme.url
    - zenodo.related_identifiers.scheme.urn
    - zenodo.related_identifiers.scheme.w3id
    - zenodo.related_identifiers.scheme.other
  date-types:
    - zenodo.date_type.accepted
    - zenodo.date_type.available
    - zenodo.date_type.collected
    - zenodo.date_type.copyrighted
    - zenodo.date_type.created
    - zenodo.date_type.issued
    - zenodo.date_type.other
    - zenodo.date_type.submitted
    - zenodo.date_type.updated
    - zenodo.date_type.valid
    - zenodo.date_type.withdrawn
  alternate-identifiers-scheme:
    - zenodo.alternate.scheme.ark
    - zenodo.alternate-identifiers.scheme.arxiv
    - zenodo.alternate-identifiers.scheme.ads
    - zenodo.alternate-identifiers.scheme.crossreffunderid
    - zenodo.alternate-identifiers.scheme.doi
    - zenodo.alternate-identifiers.scheme.ean13
    - zenodo.alternate-identifiers.scheme.eissn
    - zenodo.alternate-identifiers.scheme.grid
    - zenodo.alternate-identifiers.scheme.handle
    - zenodo.alternate-identifiers.scheme.igsn
    - zenodo.alternate-identifiers.scheme.isbn
    - zenodo.alternate-identifiers.scheme.isni
    - zenodo.alternate-identifiers.scheme.issn
    - zenodo.alternate-identifiers.scheme.istc
    - zenodo.alternate-identifiers.scheme.lissn
    - zenodo.alternate-identifiers.scheme.lsid
    - zenodo.alternate-identifiers.scheme.pmid
    - zenodo.alternate-identifiers.scheme.purl
    - zenodo.alternate-identifiers.scheme.upc
    - zenodo.alternate-identifiers.scheme.url
    - zenodo.alternate-identifiers.scheme.urn
    - zenodo.alternate-identifiers.scheme.w3id
    - zenodo.alternate-identifiers.scheme.other
  conference:
    - zenodo.conference.title
    - zenodo.conference.acronym
    - zenodo.conference.dates
    - zenodo.conference.website
    - zenodo.conference.session
    - zenodo.conference.part